-- Oracle 18c에서 계정을 생성하기 전 반드시 실행
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- LAPTOPMAN 계정 생성
CREATE USER LAPTOPMAN IDENTIFIED BY "PASSWORD";

-- 세션 생성, 접속 등의 DB 권한 부여
GRANT CREATE SESSION, CONNECT, RESOURCE TO LAPTOPMAN;

-- USERS 테이블스페이스 권한 부여
ALTER USER LAPTOPMAN DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
