--
-- 관리자 및 데이터 저장용 사용자 생성
--

-- Oracle 18c에서 계정을 생성하기 전 반드시 실행
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- LAPTOPMAN 계정 생성 (패스워드는 임의로 설정할 것)
CREATE USER LAPTOPMAN IDENTIFIED BY "PASSWORD";

-- 세션 생성, 접속, 객체(테이블, 뷰 등) 생성 DB 권한 부여
GRANT CREATE SESSION, CONNECT, RESOURCE TO LAPTOPMAN;

-- USERS 테이블스페이스 권한 부여
ALTER USER LAPTOPMAN DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;



--
-- 게스트(Guest) 사용자 생성
--

-- LAPTOPMAN_GUEST 계정 생성
CREATE USER LAPTOPMAN_GUEST IDENTIFIED BY "LAPTOPMAN";

-- 세션 생성, 접속 권한 부여
GRANT CREATE SESSION, CONNECT TO LAPTOPMAN;

-- USERS 테이블스페이스 권한 부여
ALTER USER LAPTOPMAN DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;



--
-- 게스트(Guest) 권한 설정
--
-- 읽기 전용 ROLE을 생성, LAPTOPMAN의 모든 테이블 읽기 권한을 부여
--
CREATE ROLE LAPTOPMAN_GUEST_ROLE;

BEGIN
  FOR x IN (SELECT TABLE_NAME FROM DBA_TABLES WHERE owner = 'LAPTOPMAN')
  LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT ON ' || x.TABLE_NAME || ' TO LAPTOPMAN_GUEST_ROLE';
  END LOOP;
END;

GRANT LAPTOPMAN_GUEST_ROLE TO LAPTOPMAN_GUEST;