INSERT INTO 프로그램 VALUES('리그오브레전드', '여전히 많은 사람들이 사랑하는 게임', NULL);
INSERT INTO 프로그램 VALUES('원신', '중국 miHoYo에서 제작한 3D 오픈 월드 액션 어드벤처 게임', NULL);
INSERT INTO 프로그램 VALUES('배틀그라운드', 'PUBG: BATTLEGROUNDS, 약칭 배틀그라운드는 크래프톤의 자회사인 펍지 스튜디오의 MMO 슈팅 게임이다.', NULL);
INSERT INTO 프로그램 VALUES('던전앤파이터', '던전 앤 파이터라고 띄어쓰기를 하는 경우가 많지만, 넥슨과 네오플에서 사용하는 공식 표기는 띄어쓰기 없는 던전앤파이터이다.', NULL);
INSERT INTO 프로그램 VALUES('마인크래프트', 'Mojang 스튜디오에서 2011년 정식 발매한 샌드박스 형식의 비디오 게임. 이름처럼 채광(Mine)과 제작(Craft)을 하는 게임으로 흔히 알려져 있다.', NULL);
INSERT INTO 프로그램 VALUES('검은사막', '펄어비스에서 개발 및 유통하는 대한민국의 MMORPG. 150개국 2천만 명이 플레이하는 펄어비스의 대표 게임.', NULL);
INSERT INTO 프로그램 VALUES('고스트 리콘 : 브레이크 포인트', '2019년 5월 9일에 발표된 고스트 리콘 시리즈의 최신작이자 고스트 리콘 와일드랜드의 후속작. 2019년 10월 4일 발매 했다.', NULL);
INSERT INTO 프로그램 VALUES('기어스5', '기어스 오브 워 시리즈의 5번째 작품', NULL);
INSERT INTO 프로그램 VALUES('소온 앨리시제이션리코리스', 'Aq아uria에서 3시즌 만에 개발한 소드아트온라인 파생 게임. 스토리 흐름상 페이탈 불릿 이후이며, 원작 4부를 기반으로 하여 어레인지된 스토리를룸 다', NULL);
INSERT INTO 프로그램 VALUES('디트로이트 : 비컴 휴먼', '2015년 10월 Paris Games Week에서 공개된 퀀틱 드림의 차기작으로, 그 기원은 2012년에 플레이스테이션 3 그래픽 테크데모로 발표한 프로젝트 카라다.', NULL);
INSERT INTO 프로그램 VALUES('피파온라인4', '모두가 사랑했던 그 축구게임', NULL);

INSERT INTO 프로그램사양 VALUES(0, '리그오브레전드', '최소사양', 'Intel Core i3-530', 'GeForce 410M', 1024);
INSERT INTO 프로그램사양 VALUES(0, '리그오브레전드', '권장사양', 'Intel Core i5-3330', 'GeForce GTX 560', 4096);
INSERT INTO 프로그램사양 VALUES(0, '원신', '최소사양', 'Intel Core i5-7500', 'GeForce GTX 960', 4096);
INSERT INTO 프로그램사양 VALUES(0, '원신', '권장사양', 'Intel Core i7-7700', 'GeForce GTX 1060', 8192);
INSERT INTO 프로그램사양 VALUES(0, '던전앤파이터', '최소사양', 'Intel Core 2 Duo E7500', 'Intel(R) HD Graphics 615', 8192);
INSERT INTO 프로그램사양 VALUES(0, '던전앤파이터', '권장사양', 'Intel Core 2 Duo E7500', 'GeForce 840M', 16384);
INSERT INTO 프로그램사양 VALUES(0, '배틀그라운드', '최소사양', 'Intel Core i5-4430', 'GeForce GTX 960', 8192);
INSERT INTO 프로그램사양 VALUES(0, '배틀그라운드', '권장사양', 'Intel Core i5-4430', 'GeForce GTX 960', 8192);
INSERT INTO 프로그램사양 VALUES(0, '피파온라인4', '최소사양', 'Intel Core i3-2100', 'GeForce GT 730', 2048);
INSERT INTO 프로그램사양 VALUES(0, '피파온라인4', '권장사양', 'Intel Core i5-4430', 'GeForce GTX 460', 4096);
INSERT INTO 프로그램사양 VALUES(0, '마인크래프트', '최소사양', 'Intel Core i3-3210', 'GeForce GT 440', 4096);
INSERT INTO 프로그램사양 VALUES(0, '마인크래프트', '권장사양', 'Intel Core i5-4690', 'GeForce GT 730', 8192);
INSERT INTO 프로그램사양 VALUES(0, '검은사막', '최소사양', 'Intel Core i3-8350K', 'Intel(R) HD Graphics 2500', 4096);
INSERT INTO 프로그램사양 VALUES(0, '검은사막', '권장사양', 'Intel Core i7-8700K', 'GeForce GTX 960', 8192);
INSERT INTO 프로그램사양 VALUES(0, '고스트 리콘 : 브레이크 포인트', '최소사양', 'Intel Core i5-4460', 'GeForce RTX 2060', 8192);
INSERT INTO 프로그램사양 VALUES(0, '고스트 리콘 : 브레이크 포인트', '권장사양', 'Intel Core i7-7700K', 'GeForce GTX 960', 16384);
INSERT INTO 프로그램사양 VALUES(0, '기어스5', '최소사양', 'Intel Core i3-7100', 'GeForce GTX 1050', 8192);
INSERT INTO 프로그램사양 VALUES(0, '기어스5', '권장사양', 'Intel Core i7-6900K', 'GeForce RTX 2080', 16384);
INSERT INTO 프로그램사양 VALUES(0, '디트로이트 : 비컴 휴먼', '최소사양', 'Intel Core i5-2400', 'GeForce GTX 660', 4096);
INSERT INTO 프로그램사양 VALUES(0, '디트로이트 : 비컴 휴먼', '권장사양', 'Intel Core i7-2700K', 'GeForce GTX 1080', 8192);
INSERT INTO 프로그램사양 VALUES(0, '소온 앨리시제이션리코리스', '최소사양', 'Intel Core i7-4790', 'GeForce GTX 760', 8192);
INSERT INTO 프로그램사양 VALUES(0, '소온 앨리시제이션리코리스', '권장사양', 'Intel Core i7-9700', 'GeForce GTX 1070', 16384);

INSERT INTO 프로그램지원운영체제 VALUES('원신', 'Windows');
INSERT INTO 프로그램지원운영체제 VALUES('배틀그라운드', 'Windows');
INSERT INTO 프로그램지원운영체제 VALUES('던전앤파이터', 'Windows');
INSERT INTO 프로그램지원운영체제 VALUES('리그오브레전드', 'Windows');
INSERT INTO 프로그램지원운영체제 VALUES('리그오브레전드', 'Mac OS');
INSERT INTO 프로그램지원운영체제 VALUES('피파온라인4', 'Windows');
INSERT INTO 프로그램지원운영체제 VALUES('마인크래프트', 'Windows');
INSERT INTO 프로그램지원운영체제 VALUES('마인크래프트', 'Linux');
INSERT INTO 프로그램지원운영체제 VALUES('마인크래프트', 'Mac OS');
INSERT INTO 프로그램지원운영체제 VALUES('검은사막', 'Windows');
INSERT INTO 프로그램지원운영체제 VALUES('고스트 리콘 : 브레이크 포인트', 'Windows');
INSERT INTO 프로그램지원운영체제 VALUES('기어스5', 'Windows');
INSERT INTO 프로그램지원운영체제 VALUES('디트로이트 : 비컴 휴먼', 'Windows');
INSERT INTO 프로그램지원운영체제 VALUES('소온 앨리시제이션리코리스', 'Windows');

COMMIT;